# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dat <- function(cfg) {
    .Call(`_orvacsim_rcpp_dat`, cfg)
}

rcpp_dat_small <- function(d, cfg, look, l0, l1) {
    invisible(.Call(`_orvacsim_rcpp_dat_small`, d, cfg, look, l0, l1))
}

rcpp_clin <- function(d, cfg, look) {
    .Call(`_orvacsim_rcpp_clin`, d, cfg, look)
}

rcpp_cens_visit_at_interim <- function(d_new, i, look, cfg) {
    .Call(`_orvacsim_rcpp_cens_visit_at_interim`, d_new, i, look, cfg)
}

rcpp_cens <- function(d_new, visits, i, look, cfg) {
    .Call(`_orvacsim_rcpp_cens`, d_new, visits, i, look, cfg)
}

rcpp_visits <- function(d_new, i, look, cfg) {
    .Call(`_orvacsim_rcpp_visits`, d_new, i, look, cfg)
}

rcpp_clin_set_obst <- function(d, cfg, look) {
    .Call(`_orvacsim_rcpp_clin_set_obst`, d, cfg, look)
}

rcpp_clin_interim_post <- function(m, n_uncen_0, tot_obst_0, n_uncen_1, tot_obst_1, post_draw, cfg) {
    invisible(.Call(`_orvacsim_rcpp_clin_interim_post`, m, n_uncen_0, tot_obst_0, n_uncen_1, tot_obst_1, post_draw, cfg))
}

rcpp_clin_interim_ppos <- function(d, m, nimpute, look, cfg) {
    .Call(`_orvacsim_rcpp_clin_interim_ppos`, d, m, nimpute, look, cfg)
}

rcpp_immu <- function(d, cfg, look) {
    .Call(`_orvacsim_rcpp_immu`, d, cfg, look)
}

rcpp_n_obs <- function(d, look, looks, months, info_delay) {
    .Call(`_orvacsim_rcpp_n_obs`, d, look, looks, months, info_delay)
}

rcpp_lnsero <- function(d, nobs) {
    .Call(`_orvacsim_rcpp_lnsero`, d, nobs)
}

rcpp_immu_interim_post <- function(d, nobs, post_draw, lnsero) {
    .Call(`_orvacsim_rcpp_immu_interim_post`, d, nobs, post_draw, lnsero)
}

rcpp_immu_interim_ppos <- function(d, m, nobs, nimpute, post_draw, lnsero, cfg) {
    .Call(`_orvacsim_rcpp_immu_interim_ppos`, d, m, nobs, nimpute, post_draw, lnsero, cfg)
}

atest <- function() {
    invisible(.Call(`_orvacsim_atest`))
}

rcpp_gamma <- function(n, a, b) {
    .Call(`_orvacsim_rcpp_gamma`, n, a, b)
}

rcpp_test_1 <- function(d) {
    invisible(.Call(`_orvacsim_rcpp_test_1`, d))
}

rcpp_test_sub_1 <- function(d) {
    invisible(.Call(`_orvacsim_rcpp_test_sub_1`, d))
}

rcpp_test_2 <- function(d) {
    .Call(`_orvacsim_rcpp_test_2`, d)
}

rcpp_test_sub_2 <- function(d) {
    .Call(`_orvacsim_rcpp_test_sub_2`, d)
}

