# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dat <- function(cfg) {
    .Call(`_orvacsim_rcpp_dat`, cfg)
}

rcpp_immu <- function(d, cfg, look) {
    .Call(`_orvacsim_rcpp_immu`, d, cfg, look)
}

rcpp_n_obs <- function(d, look, looks, months, info_delay) {
    .Call(`_orvacsim_rcpp_n_obs`, d, look, looks, months, info_delay)
}

rcpp_lnsero <- function(d, nobs) {
    .Call(`_orvacsim_rcpp_lnsero`, d, nobs)
}

rcpp_immu_interim_post <- function(d, nobs, post_draw, lnsero) {
    .Call(`_orvacsim_rcpp_immu_interim_post`, d, nobs, post_draw, lnsero)
}

rcpp_immu_interim_pp <- function(d, m, nobs, nimpute, post_draw, lnsero, cfg) {
    .Call(`_orvacsim_rcpp_immu_interim_pp`, d, m, nobs, nimpute, post_draw, lnsero, cfg)
}

rcpp_censoring <- function(d, look, trtstatus, iend, curmonth, surveillancemonths) {
    .Call(`_orvacsim_rcpp_censoring`, d, look, trtstatus, iend, curmonth, surveillancemonths)
}

