# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dotrial <- function(idxsim, cfg, rtn_trial_dat) {
    .Call(`_orvacsim_rcpp_dotrial`, idxsim, cfg, rtn_trial_dat)
}

rcpp_dat <- function(cfg) {
    .Call(`_orvacsim_rcpp_dat`, cfg)
}

rcpp_dat_small <- function(d, cfg, look, l0, l1) {
    invisible(.Call(`_orvacsim_rcpp_dat_small`, d, cfg, look, l0, l1))
}

rcpp_clin <- function(d, cfg, look, idxsim) {
    .Call(`_orvacsim_rcpp_clin`, d, cfg, look, idxsim)
}

rcpp_clin_set_state <- function(d, look, fu, cfg) {
    .Call(`_orvacsim_rcpp_clin_set_state`, d, look, fu, cfg)
}

rcpp_immu <- function(d, cfg, look) {
    .Call(`_orvacsim_rcpp_immu`, d, cfg, look)
}

rcpp_n_obs <- function(d, look, looks, months, info_delay) {
    .Call(`_orvacsim_rcpp_n_obs`, d, look, looks, months, info_delay)
}

rcpp_lnsero <- function(d, nobs) {
    .Call(`_orvacsim_rcpp_lnsero`, d, nobs)
}

rcpp_immu_interim_post <- function(d, m, nobs, post_draw, lnsero) {
    invisible(.Call(`_orvacsim_rcpp_immu_interim_post`, d, m, nobs, post_draw, lnsero))
}

rcpp_immu_interim_ppos <- function(d, m, look, nobs, nimpute, post_draw, lnsero, cfg) {
    .Call(`_orvacsim_rcpp_immu_interim_ppos`, d, m, look, nobs, nimpute, post_draw, lnsero, cfg)
}

rcpp_immu_ppos_test <- function(d, m, look, nobs, nimpute, post_draw, lnsero, cfg) {
    .Call(`_orvacsim_rcpp_immu_ppos_test`, d, m, look, nobs, nimpute, post_draw, lnsero, cfg)
}

rcpp_outer <- function(z, t, out) {
    invisible(.Call(`_orvacsim_rcpp_outer`, z, t, out))
}

rcpp_logrank <- function(d, look, cfg) {
    .Call(`_orvacsim_rcpp_logrank`, d, look, cfg)
}

rcpp_gamma <- function(n, a, b) {
    .Call(`_orvacsim_rcpp_gamma`, n, a, b)
}

