---
title: "Simulations to explore accrual/power relation in orvac code"
author: "Mark Jones"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: yes
    self_contained: yes
    theme: united
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    toc: yes
    toc_depth: '3'
geometry: left=0.2cm,right=0.2cm,top=1cm,bottom=1cm
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = 'figs/')

suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(doParallel))
suppressPackageStartupMessages(library(foreach))
suppressPackageStartupMessages(library(poisson))
source("../sim_01/util.R")
library(orvacsim)

ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text = element_text(size = 10))
ggplot2::theme_update(legend.position = "top")
ggplot2::theme_update(axis.text.x = element_text(size = 10))
ggplot2::theme_update(axis.text.y = element_text(size = 10))

# Work|Right|Fast
# rmarkdown::render("simulation_report.Rmd", clean=TRUE)
```

# Preamble 

Now look at the relationship between accrual and power in orvac. 

```{r}

mainloop <- function(nsim = 2, 
                     med0 = 30, 
                     med1 = 35, 
                     fu = 36, 
                     idx_interim = 20,
                     cluster = T){
  
  beta_tte <- function(med0, med1){
    b0 <- log(2)/med0
    b1 <- log(2)/med1 - b0
    list(b0 = b0, b1 = b1)
  }
  
  # accrual at 30
  cfg1 <- readRDS("cfg-30.RDS")
  
  # updates
  cfg1$max_age_fu_months <- fu
  ttebeta <- beta_tte(med0, med1)
  cfg1$b0tte <- ttebeta$b0
  cfg1$b1tte <- ttebeta$b1
  
  # create data
  d1 <- lapply(1:nsim, function(x) rcpp_dat(cfg1))
  summary(d1[[1]])
  
  # accrual at 50
  cfg2 <- readRDS("cfg-50.RDS")
  
  # updates
  cfg2$max_age_fu_months <- fu
  ttebeta <- beta_tte(med0, med1)
  cfg1$b0tte <- ttebeta$b0
  cfg1$b1tte <- ttebeta$b1
  
  # create data
  d2 <- lapply(1:nsim, function(x) rcpp_dat(cfg2))
  summary(d2[[1]])
 
  if(cluster){
    cl <- makeCluster(parallel::detectCores() , outfile="")
    registerDoParallel(cl)
  } else {
    registerDoSEQ()
  }
  
  results <- foreach(i = 1:nsim,
                     .packages = c("orvacsim"),
                     .errorhandling = 'pass'
  ) %dopar%{
    
    test1 <- rcpp_clin(d1[[i]], cfg1, idx_interim, i)
    test2 <- rcpp_clin(d2[[i]], cfg2, idx_interim, i)
  
    m <- array(c(test1$ppn, test2$ppn), dim = c(1, 2)) 
    
    mynames <- c(paste0("accr_", 
                      c(cfg1$people_per_interim_period,
                        cfg2$people_per_interim_period)))
    names(m) <- mynames
    return(list(m = m))
  }
  if(cluster){
    stopCluster(cl)
  }
  
  results
}

```

Looking at:

+ a fixed interim
+ differing fu
+ differing median tte baseline and diff

# Expt 1

```{r}
nsim <- 2

med0 = 30 
med1 = 30 
fu = 36
idx_interim = 20

starttime <- Sys.time()
results <- mainloop(nsim, med0, med1, fu, idx_interim)
res1 <- do.call(rbind, lapply(1:nsim, function(x) unlist(results[[x]])))
endtime <- Sys.time()
difftime(endtime, starttime, units = "hours")
mymeans <- c(expt = 1, colMeans(res1))
```


# Expt 2

```{r}
med0 = 30 
med1 = 40 
fu = 36
idx_interim = 20

starttime <- Sys.time()
results <- mainloop(nsim, med0, med1, fu, idx_interim)
res1 <- do.call(rbind, lapply(1:nsim, function(x) unlist(results[[x]])))
endtime <- Sys.time()
difftime(endtime, starttime, units = "hours")
colMeans(res1)
mymeans <- rbind(mymeans, 
                 c(expt = 2, colMeans(res1)))
```

# Expt 3

```{r}
med0 = 30 
med1 = 35 
fu = 75
idx_interim = 20

starttime <- Sys.time()
results <- mainloop(nsim, med0, med1, fu, idx_interim)
res1 <- do.call(rbind, lapply(1:nsim, function(x) unlist(results[[x]])))
endtime <- Sys.time()
difftime(endtime, starttime, units = "hours")
colMeans(res1)
mymeans <- rbind(mymeans, 
                 c(expt = 3, colMeans(res1)))
```

# Expt 4

```{r}
med0 = 30 
med1 = 40 
fu = 75
idx_interim = 20

starttime <- Sys.time()
results <- mainloop(nsim, med0, med1, fu, idx_interim)
res1 <- do.call(rbind, lapply(1:nsim, function(x) unlist(results[[x]])))
endtime <- Sys.time()
difftime(endtime, starttime, units = "hours")
colMeans(res1)
mymeans <- rbind(mymeans, 
                 c(expt = 4, colMeans(res1)))
```

# Expt 5

```{r}
med0 = 20 
med1 = 30 
fu = 36
idx_interim = 20

starttime <- Sys.time()
results <- mainloop(nsim, med0, med1, fu, idx_interim)
res1 <- do.call(rbind, lapply(1:nsim, function(x) unlist(results[[x]])))
endtime <- Sys.time()
difftime(endtime, starttime, units = "hours")
colMeans(res1)
mymeans <- rbind(mymeans, 
                 c(expt = 5, colMeans(res1)))
```

# Expt 6

```{r}
med0 = 20 
med1 = 30 
fu = 75
idx_interim = 20

starttime <- Sys.time()
results <- mainloop(nsim, med0, med1, fu, idx_interim)
res1 <- do.call(rbind, lapply(1:nsim, function(x) unlist(results[[x]])))
endtime <- Sys.time()
difftime(endtime, starttime, units = "hours")
colMeans(res1)
mymeans <- rbind(mymeans, 
                 c(expt = 6, colMeans(res1)))
rownames(mymeans) <- NULL
```



```{r, fig.width = 4, fig.height=5, fig.cap="Probability of ES by accrual"}
dfig <- as.data.frame(mymeans) %>% 
  tidyr::gather(key = "accrual", value = "prob_es", -expt)

ggplot(dfig, aes(x = expt, y = prob_es, colour = paste0(accrual)))+
  geom_point()+
  scale_color_discrete("Enrolled per 3 months")
```

